# Generated by Django 5.1.6 on 2025-04-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0032_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mtn_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('telecel_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('airteltigo_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ecobank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gtbank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fidelity_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calbank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('access_bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.owner')),
            ],
        ),
    ]
