# Generated by Django 5.1.6 on 2025-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_rename_access_bank_balance_ownerbalance_absa_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_1_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_2_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_3_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_4_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_5_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
