# Generated by Django 5.1.6 on 2025-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_ownerbalance_debtor_1_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_10_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_6_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_7_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_8_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_9_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name10',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name7',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name8',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerbalance',
            name='debtor_name9',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
