# Generated by Django 5.1.6 on 2025-02-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('Please select cash at location', 'Please select cash at location'), ('Cash @ location', 'Cash @ location'), ('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('ECOBANK', 'ECOBANK'), ('PAN AFRICA', 'PAN AFRICA'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM TANOSO', 'MELCOM TANOSO'), ('MELCOM MANHYIA', 'MELCOM MANHYIA'), ('MELCOM TAFO', 'MELCOM TAFO'), ('MELCOM AHODWO', 'MELCOM AHODWO'), ('MELCOM ADUM', 'MELCOM ADUM'), ('MELCOM SUAME', 'MELCOM SUAME')], max_length=100),
        ),
    ]
