# Generated by Django 5.1.6 on 2025-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_owner_email_owner_full_name_owner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='agent_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='company_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='digital_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
