# Generated by Django 5.1.6 on 2025-03-06 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('AGENT', 'Agent'), ('CUSTOMER', 'Customer'), ('MOBILIZATION', 'Mobilization')], max_length=12),
        ),
        migrations.CreateModel(
            name='Mobilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_number', models.CharField(blank=True, max_length=10, null=True)),
                ('digital_address', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.owner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobilization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
