# Generated by Django 5.1.6 on 2025-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_mobilizationcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('BRANCH', 'Branch'), ('CUSTOMER', 'Customer'), ('MOBILIZATION', 'Mobilization')], max_length=12),
        ),
    ]
