# Generated by Django 5.1.6 on 2025-03-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_user_owner_owner_alter_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
