# Generated by Django 5.1.6 on 2025-03-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='mobilization',
            old_name='user',
            new_name='mobilization',
        ),
    ]
