# Generated by Django 5.1.6 on 2025-03-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mobilization'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.agent'),
        ),
        migrations.AlterField(
            model_name='mobilization',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.owner'),
        ),
    ]
