# Generated by Django 5.1.6 on 2025-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customer_customer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
