# Generated by Django 5.1.6 on 2025-03-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_otp_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='customer_image'),
        ),
    ]
