# Generated by Django 5.1.6 on 2025-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customer_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='customer_image/'),
        ),
    ]
