# Generated by Django 5.1.6 on 2025-04-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
