# Generated by Django 5.2 on 2025-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_oil_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_oil_change_mileage',
            field=models.PositiveBigIntegerField(default=0, help_text='Mileage at last oil change (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='oil_change_default',
            field=models.PositiveBigIntegerField(default=5000, help_text='Default mileage between oil changes (km)'),
        ),
    ]
