# Generated by Django 5.1.6 on 2025-05-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_vehicle_last_oil_change_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'Kilometers'), ('mi', 'Miles')], default='km', help_text="Unit of measurement for this vehicle's odometer", max_length=2),
        ),
    ]
