# Generated by Django 5.1.6 on 2025-05-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_vehicle_driver_vehicle_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='admin',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.owner'),
        ),
    ]
