# Generated by Django 5.1.6 on 2025-05-21 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('BRANCH', 'Branch'), ('CUSTOMER', 'Customer'), ('MOBILIZATION', 'Mobilization'), ('DRIVER', 'Driver'), ('ACCOUNTANT', 'Accountant')], max_length=12),
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_number', models.CharField(blank=True, max_length=10, null=True)),
                ('digital_address', models.CharField(blank=True, max_length=50, null=True)),
                ('accountant_code', models.CharField(blank=True, max_length=20, null=True)),
                ('accountant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
