# Generated by Django 5.1.6 on 2025-05-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_role_accountant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
    ]
