# Generated by Django 5.1.6 on 2025-04-28 14:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0034_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_mileage', models.PositiveIntegerField()),
                ('end_mileage', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vehicle')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
