# Generated by Django 5.1.6 on 2025-04-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileagerecord',
            name='notes',
        ),
    ]
