# Generated by Django 5.1.6 on 2025-05-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_notification'),
        ('users', '0035_vehicle_last_oil_change_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchange',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
    ]
