# Generated by Django 5.1.6 on 2025-05-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_oilchange_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='station_name',
            field=models.CharField(blank=True, choices=[('Shell', 'Shell'), ('Goil', 'Goil'), ('Total', 'Total'), ('ZEN', 'ZEN')], max_length=100, null=True),
        ),
    ]
