# Generated by Django 5.1.6 on 2025-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_alter_fuelrecord_station_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('oil', 'Oil'), ('repair', 'Repair'), ('toll', 'Toll Fee'), ('parking', 'Parking Fee'), ('other', 'Other')], max_length=20),
        ),
    ]
