# Generated by Django 5.1.6 on 2025-05-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_alter_expense_type'),
        ('users', '0043_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicle'),
        ),
        migrations.AlterField(
            model_name='mileagerecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicle'),
        ),
        migrations.AlterField(
            model_name='oilchange',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vehicle'),
        ),
    ]
