# Generated by Django 5.1.6 on 2025-03-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0004_paymentrequest'),
        ('users', '0014_mobilizationcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=16)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mobilizationcustomer')),
            ],
        ),
    ]
