# Generated by Django 5.1.6 on 2025-03-09 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0005_customeraccount'),
        ('users', '0014_mobilizationcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customeraccounts', to='users.mobilizationcustomer'),
        ),
    ]
