# Generated by Django 5.1.6 on 2025-03-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0006_alter_customeraccount_customer'),
        ('users', '0014_mobilizationcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('d_200', models.CharField(blank=True, max_length=12, null=True)),
                ('d_100', models.CharField(blank=True, max_length=12, null=True)),
                ('d_50', models.CharField(blank=True, max_length=12, null=True)),
                ('d_20', models.CharField(blank=True, max_length=12, null=True)),
                ('d_10', models.CharField(blank=True, max_length=12, null=True)),
                ('d_5', models.CharField(blank=True, max_length=12, null=True)),
                ('d_2', models.CharField(blank=True, max_length=12, null=True)),
                ('d_1', models.CharField(blank=True, max_length=12, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('mobilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mobilization')),
            ],
        ),
    ]
