# Generated by Django 5.1.6 on 2025-03-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0008_alter_tellercalculator_d_1_and_more'),
        ('users', '0024_customer_mobilization_alter_customer_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customeraccounts', to='users.customer'),
        ),
    ]
