# Generated by Django 5.1.6 on 2025-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0009_alter_customeraccount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
