# Generated by Django 5.1.6 on 2025-03-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0010_bankdeposit_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdeposit',
            old_name='transaction_id',
            new_name='agent_transaction_id',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='transaction_id',
            new_name='agent_transaction_id',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='owner_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='owner_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
