# Generated by Django 5.1.6 on 2025-03-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0011_rename_transaction_id_bankdeposit_agent_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdeposit',
            old_name='agent_transaction_id',
            new_name='mobilization_transaction_id',
        ),
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='agent_transaction_id',
            new_name='mobilization_transaction_id',
        ),
    ]
