# Generated by Django 5.1.6 on 2025-03-18 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0012_rename_agent_transaction_id_bankdeposit_mobilization_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='mobilization_transaction_id',
        ),
    ]
