# Generated by Django 5.1.6 on 2025-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0013_remove_bankdeposit_mobilization_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwithdrawal',
            name='ghana_card',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ghana_card_img/'),
        ),
    ]
