# Generated by Django 5.1.6 on 2025-03-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0014_bankwithdrawal_ghana_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdeposit',
            options={'ordering': ['-date_deposited']},
        ),
        migrations.AlterModelOptions(
            name='bankwithdrawal',
            options={'ordering': ['-date_withdrawn']},
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
