# Generated by Django 5.1.6 on 2025-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0015_alter_bankdeposit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='receipt',
            field=models.ImageField(blank=True, default='', null=True, upload_to='receipt_img/'),
        ),
    ]
