# Generated by Django 5.1.6 on 2025-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0016_bankdeposit_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot',
            field=models.ImageField(blank=True, default='', null=True, upload_to='screenshot_img/'),
        ),
    ]
