# Generated by Django 5.1.6 on 2025-03-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0017_bankdeposit_screenshot'),
        ('users', '0027_user_otp_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('mobilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mobilization')),
            ],
        ),
    ]
