# Generated by Django 5.1.6 on 2025-03-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0018_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_img/'),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img/'),
        ),
    ]
