# Generated by Django 5.1.6 on 2025-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0019_alter_bankdeposit_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipt_img/'),
        ),
    ]
