# Generated by Django 5.1.6 on 2025-03-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0020_alter_bankdeposit_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipt_img/'),
        ),
    ]
