# Generated by Django 5.1.6 on 2025-03-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0021_alter_bankdeposit_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
