# Generated by Django 5.1.6 on 2025-03-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0022_alter_bankdeposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
