# Generated by Django 5.1.6 on 2025-03-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0023_alter_bankdeposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot10',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img10/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img2/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot3',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img3/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot4',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img4/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot5',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img5/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot6',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img6/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot7',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img7/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot8',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img8/'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='screenshot9',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot_img9/'),
        ),
    ]
