# Generated by Django 5.1.6 on 2025-03-31 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0027_mobilizationaccount'),
        ('mobilization', '0024_bankdeposit_screenshot10_bankdeposit_screenshot2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.mobilizationaccount'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.mobilizationaccount'),
        ),
    ]
