# Generated by Django 5.1.6 on 2025-03-31 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0025_bankdeposit_account_paymentrequest_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
