# Generated by Django 5.1.6 on 2025-04-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0026_alter_bankdeposit_amount_alter_paymentrequest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='account',
        ),
    ]
