# Generated by Django 5.1.6 on 2025-05-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0027_remove_bankdeposit_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='mobilization_transaction_id',
        ),
    ]
