# Generated by Django 5.2 on 2025-08-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilization', '0030_alter_paymentrequest_bank'),
        ('users', '0043_remove_vehicle_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashECashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_type', models.CharField(choices=[('Telco', 'Telco'), ('Cash', 'Cash')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('network', models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('MTN', 'MTN'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], default='Select Network', max_length=20, null=True)),
                ('cash', models.CharField(blank=True, choices=[('Cash', 'Cash')], max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrears', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('mobilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_and_ecash_requests', to='users.mobilization')),
            ],
        ),
    ]
