# Generated by Django 5.1.6 on 2025-02-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
    ]
