# Generated by Django 5.1.6 on 2025-02-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_customeraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccount',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
