# Generated by Django 5.1.6 on 2025-02-25 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_customeraccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bank'),
        ),
    ]
