# Generated by Django 5.1.6 on 2025-02-26 13:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_drawer'),
        ('users', '0007_customer_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFloatAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mtn_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('telecel_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ecobank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fidelity_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calbank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gtbank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cash_at_hand', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capital_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_float_drawers', to='users.agent')),
            ],
        ),
    ]
