# Generated by Django 5.1.6 on 2025-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_efloataccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='efloataccount',
            name='access_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='efloataccount',
            name='airtel_tigo_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
