# Generated by Django 5.1.6 on 2025-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_efloataccount_access_bank_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
