# Generated by Django 5.1.6 on 2025-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_customeraccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efloataccount',
            name='capital_amount',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
    ]
