# Generated by Django 5.1.6 on 2025-03-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_alter_efloataccount_capital_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efloataccount',
            name='capital_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
