# Generated by Django 5.1.6 on 2025-03-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_alter_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentAtBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('d_200', models.IntegerField(blank=True, default=0)),
                ('d_100', models.IntegerField(blank=True, default=0)),
                ('d_50', models.IntegerField(blank=True, default=0)),
                ('d_20', models.IntegerField(blank=True, default=0)),
                ('d_10', models.IntegerField(blank=True, default=0)),
                ('d_5', models.IntegerField(blank=True, default=0)),
                ('d_2', models.IntegerField(blank=True, default=0)),
                ('d_1', models.IntegerField(blank=True, default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
