# Generated by Django 5.1.6 on 2025-03-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0016_customerpaymentatbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
