# Generated by Django 5.1.6 on 2025-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0018_remove_customerpaymentatbank_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentatbank',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
