# Generated by Django 5.1.6 on 2025-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0020_remove_customerpaymentatbank_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_10',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_100',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_20',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_200',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_50',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
