# Generated by Django 5.1.6 on 2025-03-09 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0022_alter_bank_name'),
        ('users', '0014_mobilizationcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.customer'),
        ),
    ]
