# Generated by Django 5.1.6 on 2025-03-10 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0023_alter_customeraccount_customer'),
        ('users', '0014_mobilizationcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpaymentatbank',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.agent'),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_1',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_10',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_100',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_20',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_200',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_5',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='d_50',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
