# Generated by Django 5.1.6 on 2025-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0025_alter_customerpaymentatbank_d_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentatbank',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
