# Generated by Django 5.1.6 on 2025-03-31 04:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0027_mobilizationaccount'),
        ('users', '0029_alter_customer_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationaccount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mobilizationaccount',
            name='mobilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mobilization'),
        ),
    ]
