# Generated by Django 5.1.6 on 2025-03-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0029_rename_opening_balance_mobilizationaccount_balance_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='mobilizationaccount',
            name='balance_left',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
    ]
