# Generated by Django 5.1.6 on 2025-03-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0030_mobilizationaccount_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizationaccount',
            name='balance_left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
