# Generated by Django 5.1.6 on 2025-03-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0031_alter_mobilizationaccount_balance_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilizationaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='mobilizationaccount',
            name='opening_balance',
        ),
    ]
