# Generated by Django 5.1.6 on 2025-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0034_alter_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='efloataccount',
            name='absa_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
