# Generated by Django 5.1.6 on 2025-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_remove_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
