# Generated by Django 5.1.6 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_remove_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default=True, max_length=50, null=True, unique=True),
        ),
    ]
