# Generated by Django 5.1.6 on 2025-05-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
