# Generated by Django 5.1.6 on 2025-05-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_alter_transaction_transaction_id'),
        ('users', '0042_alter_user_role_accountant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.vehicle'),
        ),
    ]
