# Generated by Django 5.1.6 on 2025-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0010_branch_transaction_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('HO', 'Head Office'), ('KEJ', 'Kejetia Branch'), ('DVL', 'DVLA Branch'), ('ADM', 'Adum Melcom'), ('ADX', 'Adum Annex Melcom'), ('TAN', 'Tanoso Melcom'), ('SUA', 'Suame Melcom'), ('SAN', 'Santasi Melcom'), ('AHO', 'Ahodwo Melcom'), ('TAC', 'Taco Melcom'), ('KUM', 'Kumasi Mall'), ('MAN', 'Manhyia Melcom'), ('TOF', 'Tofo Melcom'), ('MOB', 'Mobilization Team')], max_length=100),
        ),
    ]
