# Generated by Django 5.1.6 on 2025-05-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0011_remove_branch_code_alter_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='network_or_bank',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN'), ('Ecobank', 'Ecobank')], max_length=100, null=True),
        ),
    ]
