# Generated by Django 5.1.6 on 2025-05-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0012_transaction_network_or_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accountant.branch'),
        ),
    ]
