# Generated by Django 5.1.6 on 2025-05-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0013_alter_transaction_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('HO', 'Head Office'), ('KEJ', 'Kejetia Branch'), ('DVL', 'DVLA Branch'), ('ADM', 'Adum Melcom'), ('ADX', 'Adum Annex Melcom'), ('TAN', 'Tanoso Melcom'), ('SUA', 'Suame Melcom'), ('SAN', 'Santasi Melcom'), ('AHO', 'Ahodwo Melcom'), ('KUM', 'Kumasi Mall'), ('MAN', 'Manhyia Melcom'), ('TAF', 'Tafo Melcom'), ('MOB', 'Mobilization Team')], max_length=100),
        ),
    ]
