# Generated by Django 5.1.6 on 2025-05-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0014_rename_make_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
