# Generated by Django 5.1.6 on 2025-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0015_vehicle_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(choices=[('Head Office', 'Head Office'), ('Kejetia Branch', 'Kejetia Branch'), ('DVLA Branch', 'DVLA Branch'), ('Adum Melcom', 'Adum Melcom'), ('Adum Annex Melcom', 'Adum Annex Melcom'), ('Tanoso Melcom', 'Tanoso Melcom'), ('Suame Melcom', 'Suame Melcom'), ('Santasi Melcom', 'Santasi Melcom'), ('Ahodwo Melcom', 'Ahodwo Melcom'), ('Kumasi Mall', 'Kumasi Mall'), ('Manhyia Melcom', 'Manhyia Melcom'), ('Tafo Melcom', 'Tafo Melcom'), ('Mobilization Team', 'Mobilization Team'), ('TLGhana', 'TLGhana')], max_length=100),
        ),
    ]
