# Generated by Django 5.1.6 on 2025-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0016_alter_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='network_or_bank',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('MTN', 'MTN'), ('Ecobank', 'Ecobank')], max_length=100, null=True),
        ),
    ]
