# Generated by Django 5.1.6 on 2025-02-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercashin',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('Loading', 'Loading'), ('Deposit', 'Deposit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customercashin',
            name='network',
            field=models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], default='Select Network', max_length=20),
        ),
    ]
