# Generated by Django 5.1.6 on 2025-02-27 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_customercashin_deposit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercashin',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='CustomerCashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], default='Select Network', max_length=20)),
                ('customer_phone', models.CharField(blank=True, max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('date_withdrawn', models.DateField(auto_now_add=True)),
                ('time_withdrawn', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cash_outs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
