# Generated by Django 5.1.6 on 2025-02-28 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_bankdeposit_bank_alter_bankdeposit_status'),
        ('users', '0007_customer_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=15)),
                ('bank', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_withdrawn', models.DateField(default=django.utils.timezone.now)),
                ('time_withdrawn', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdrawals', to='users.agent')),
            ],
        ),
    ]
