# Generated by Django 5.1.6 on 2025-02-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_bankwithdrawal'),
        ('users', '0008_alter_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAndECashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_type', models.CharField(choices=[('Bank', 'Bank'), ('Telco', 'Telco'), ('Cash', 'Cash')], max_length=10)),
                ('bank', models.CharField(blank=True, choices=[('Ecobank', 'Ecobank'), ('Fidelity', 'Fidelity'), ('Calbank', 'Calbank'), ('GTBank', 'GTBank'), ('Access Bank', 'Access Bank')], max_length=20, null=True)),
                ('network', models.CharField(blank=True, choices=[('MTN', 'MTN'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_and_ecash_requests', to='users.agent')),
            ],
        ),
    ]
