# Generated by Django 5.1.6 on 2025-02-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_cashandecashrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashandecashrequest',
            old_name='date_requested',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='cashandecashrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cashandecashrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
