# Generated by Django 5.1.6 on 2025-02-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_rename_date_requested_cashandecashrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashandecashrequest',
            name='bank',
            field=models.CharField(blank=True, choices=[('Ecobank', 'Ecobank'), ('Fidelity', 'Fidelity'), ('Calbank', 'Calbank'), ('GTBank', 'GTBank'), ('Access Bank', 'Access Bank')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashandecashrequest',
            name='network',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], default='', max_length=20, null=True),
        ),
    ]
