# Generated by Django 5.1.6 on 2025-02-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_alter_cashandecashrequest_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashandecashrequest',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
