# Generated by Django 5.1.6 on 2025-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_customercomplain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplain',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
