# Generated by Django 5.1.6 on 2025-03-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_holdcustomeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdcustomeraccount',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
