# Generated by Django 5.1.6 on 2025-03-02 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_holdcustomeraccount_amount'),
        ('users', '0011_alter_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=10)),
                ('reasons', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.agent')),
            ],
        ),
    ]
