# Generated by Django 5.1.6 on 2025-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_customerfraud_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercashin',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('Loading', 'Loading'), ('Direct', 'Direct')], max_length=20),
        ),
    ]
