# Generated by Django 5.1.6 on 2025-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_paymentrequest_name_alter_paymentrequest_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashandecashrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cashandecashrequest',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
