# Generated by Django 5.1.6 on 2025-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0022_alter_cashandecashrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
