# Generated by Django 5.1.6 on 2025-03-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0024_rename_amount_customercashin_amount_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercashin',
            old_name='amount_sent',
            new_name='amount',
        ),
    ]
