# Generated by Django 5.1.6 on 2025-03-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0026_customercashout_cash_paid_cashoutcommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashincommission',
            name='customer_cash_in',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashincommission', to='agent.customercashin'),
        ),
        migrations.AlterField(
            model_name='cashoutcommission',
            name='customer_cash_out',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashoutcommission', to='agent.customercashout'),
        ),
    ]
