# Generated by Django 5.1.6 on 2025-03-06 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0027_alter_cashincommission_customer_cash_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCashInCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_cash_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agent.customercashin')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedCustomerCashIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, choices=[('Select Network', 'Select Network'), ('Mtn', 'Mtn'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], default='Select Network', max_length=20)),
                ('customer_phone', models.CharField(blank=True, max_length=10)),
                ('deposit_type', models.CharField(blank=True, choices=[('Loading', 'Loading'), ('Direct', 'Direct')], max_length=20)),
                ('depositor_name', models.CharField(blank=True, default='', max_length=30)),
                ('depositor_number', models.CharField(blank=True, default='', max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('date_deposited', models.DateField(auto_now_add=True)),
                ('time_deposited', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
