# Generated by Django 5.1.6 on 2025-03-07 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0028_archivedcashincommission_archivedcustomercashin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, choices=[('Mtn', 'Mtn'), ('Telecel', 'Telecel'), ('AirtelTigo', 'AirtelTigo')], default='Select Network', max_length=20)),
                ('deposit_type', models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Merchant', 'Merchant')], max_length=20)),
                ('agent_number', models.CharField(blank=True, default='', max_length=30)),
                ('merchant_code', models.CharField(blank=True, default='', max_length=30)),
                ('merchant_number', models.CharField(blank=True, default='', max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('date_deposited', models.DateField(auto_now_add=True)),
                ('time_deposited', models.TimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pay_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
