# Generated by Django 5.1.6 on 2025-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0029_customerpayto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayto',
            name='sent_to_agent_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customerpayto',
            name='agent_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
