# Generated by Django 5.1.6 on 2025-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0030_customerpayto_sent_to_agent_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercashin',
            name='is_fraudster',
            field=models.BooleanField(default=False),
        ),
    ]
