# Generated by Django 5.1.6 on 2025-03-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0031_customercashin_is_fraudster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayto',
            name='agent_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
