# Generated by Django 5.1.6 on 2025-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0033_bankwithdrawal_ghana_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankwithdrawal',
            name='ghana_card',
            field=models.ImageField(blank=True, null=True, upload_to='ghana_card/'),
        ),
    ]
