# Generated by Django 5.1.6 on 2025-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0034_alter_bankwithdrawal_ghana_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='status',
        ),
    ]
