# Generated by Django 5.1.6 on 2025-03-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0035_remove_bankdeposit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankwithdrawal',
            name='ghana_card',
            field=models.ImageField(blank=True, default='', null=True, upload_to='ghana_card_img/'),
        ),
    ]
