# Generated by Django 5.1.6 on 2025-03-25 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0036_alter_bankwithdrawal_ghana_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpayto',
            old_name='deposit_type',
            new_name='transfer_type',
        ),
        migrations.RemoveField(
            model_name='customerpayto',
            name='sent_to_agent_number',
        ),
    ]
