# Generated by Django 5.1.6 on 2025-03-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0037_rename_deposit_type_customerpayto_transfer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='receipt',
            field=models.ImageField(blank=True, default='', null=True, upload_to='branch_receipt_img/'),
        ),
    ]
