# Generated by Django 5.1.6 on 2025-03-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0039_report'),
        ('users', '0027_user_otp_verified_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='BranchReport',
        ),
    ]
