# Generated by Django 5.1.6 on 2025-04-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0041_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_deposited',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='time_deposited',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_succussful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('PAY_TO', 'Pay To'), ('AGENT_PAYOUT', 'Agent Payout')], max_length=12),
        ),
    ]
