# Generated by Django 5.1.6 on 2025-04-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0042_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashandecashrequest',
            name='cash',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash')], max_length=10, null=True),
        ),
    ]
