# Generated by Django 5.1.6 on 2025-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0043_cashandecashrequest_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='branch_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
