# Generated by Django 5.1.6 on 2025-04-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0044_paymentrequest_branch_transaction_id'),
        ('users', '0032_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercashin',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cash_ins', to='users.agent'),
        ),
        migrations.AlterField(
            model_name='customercashout',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cash_outs', to='users.agent'),
        ),
    ]
