# Generated by Django 5.1.6 on 2025-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0045_alter_customercashin_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
