# Generated by Django 5.1.6 on 2025-04-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0046_bankdeposit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='status',
        ),
    ]
