# Generated by Django 5.1.6 on 2025-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0047_remove_bankdeposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashandecashrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashandecashrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
