# Generated by Django 5.1.6 on 2025-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0048_cashandecashrequest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashandecashrequest',
            name='bank',
            field=models.CharField(blank=True, choices=[('Select Bank', 'Select Bank'), ('Ecobank', 'Ecobank'), ('Fidelity', 'Fidelity'), ('Calbank', 'Calbank'), ('GTBank', 'GTBank'), ('Access Bank', 'Access Bank')], default='Select Bank', max_length=50, null=True),
        ),
    ]
