# Generated by Django 5.1.6 on 2025-04-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0049_alter_cashandecashrequest_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashandecashrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
