# Generated by Django 5.2 on 2025-05-02 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0051_userbalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBalance',
            new_name='UserWallet',
        ),
    ]
