# Generated by Django 5.1.6 on 2025-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0052_rename_userbalance_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashandecashrequest',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
