# Generated by Django 5.1.6 on 2025-05-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0053_cashandecashrequest_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='branch_transaction_id',
        ),
    ]
