# Generated by Django 5.1.6 on 2025-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0055_paymentrequest_branch_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_succussful',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('PAY_TO', 'Pay To'), ('AGENT_PAYOUT', 'Agent Payout')], max_length=20),
        ),
    ]
