# Generated by Django 5.1.6 on 2025-06-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0057_alter_paymentrequest_bank'),
        ('users', '0043_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayto',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pay_to', to='users.agent'),
        ),
    ]
