# Generated by Django 5.1.6 on 2025-07-16 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0058_alter_customerpayto_agent'),
        ('users', '0043_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to='users.branch'),
        ),
        migrations.CreateModel(
            name='BranchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='users.branch')),
            ],
        ),
    ]
