# Generated by Django 5.1.6 on 2025-08-22 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0058_alter_customerpayto_agent'),
        ('users', '0043_remove_vehicle_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accounts', to='users.branch')),
            ],
        ),
    ]
