# Generated by Django 5.1.6 on 2025-09-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0059_branchaccount'),
        ('users', '0045_alter_agent_branch_alter_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
    ]
