# Generated by Django 5.1.6 on 2025-07-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0059_bankdeposit_branch_branchaccount'),
        ('users', '0043_remove_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwithdrawal',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdrawals', to='users.branch'),
        ),
        migrations.AddField(
            model_name='cashandecashrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_and_ecash_requests', to='users.branch'),
        ),
    ]
