# Generated by Django 5.1.6 on 2025-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0059_branchaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='branch',
            field=models.CharField(blank=True, choices=[('DVLA', 'DVLA'), ('HEAD OFFICE', 'HEAD OFFICE'), ('KEJETIA', 'KEJETIA'), ('MELCOM SANTASI', 'MELCOM SANTASI'), ('MELCOM TANOSO', 'MELCOM TANOSO'), ('MELCOM MANHYIA', 'MELCOM MANHYIA'), ('MELCOM TAFO', 'MELCOM TAFO'), ('AHODWO MELCOM', 'AHODWO MELCOM'), ('ADUM MELCOM', 'ADUM MELCOM'), ('MELCOM SUAME', 'MELCOM SUAME'), ('KUMASI MALL MELCOM', 'KUMASI MALL MELCOM')], max_length=30, null=True),
        ),
    ]
